############################################################
# Dockerfile to build cashcowd container images
# Based on Ubuntu
############################################################

FROM ubuntu:14.04
MAINTAINER laudney

RUN apt-get update
RUN apt-get install -y git make g++ python-leveldb libboost-all-dev libssl-dev libdb++-dev pkg-config libminiupnpc-dev wget xz-utils
RUN apt-get clean

RUN adduser cashcow --disabled-password
USER cashcow

WORKDIR /home/cashcow
RUN mkdir bin src
RUN echo PATH=\"\$HOME/bin:\$PATH\" >> .bash_profile

WORKDIR /home/cashcow/src
RUN git clone https://github.com/cashcow-project/cashcow.git

WORKDIR	/home/cashcow/src/cashcow/src
RUN make -f makefile.unix
RUN strip cashcowd
RUN cp -f cashcowd /home/cashcow/bin/
RUN make -f makefile.unix clean

WORKDIR	 /home/cashcow
RUN mkdir .cashcow
RUN cp -f src/cashcow/contrib/docker/cashcow.conf .cashcow/

WORKDIR /home/cashcow/.cashcow
RUN wget -q https://github.com/cashcow-project/cashcow/releases/download/v1.3.1.2/bootstrap.dat.xz

ENV HOME /home/cashcow
EXPOSE 8332
USER cashcow
